name: Testing and Building my app
on: push
jobs:
  test:
    runs-on: ubuntu-slim
    steps:
      - name: getting my code first
        uses: actions/checkout@v6
      - name: installing node
        uses: actions/setup-node@v6
        with:
          node-version: '22.15.1'
      - name: installing dependencies
        run: npm ci
      - name: testing app
        run: npm test      



      